version: "3"
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/go/src/github.com/takanorifukuyama/go-api/api
    links:
      - database
    environment:
      - DB_NAME=go-api
  database:
    image: mongo:3.0
    command mongo --smallfiles --quiet --logpath=/dev/null
